version: 0.0
os: linux
files:
  - source: /backend
    destination: /home/ec2-user/backend
  - source: /frontend
    destination: /home/ec2-user/frontend
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: deploy_scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/run.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: deploy_scripts/validate.sh
      timeout: 60
      runas: ec2-user
