version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing
  pre_build:
    commands:
      - cd backend
      - echo Installing source NPM dependencies with npm ci
      - npm ci
      - echo Installing source NPM dependencies with npm install
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
